#install chocolatey
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#install chocolatey distributed tools
choco install chromium -y
choco install docker-desktop -y
choco install drawio -y
choco install etcher -y
choco install firefox -y
choco install git -y
choco install gitkraken -y
choco install git-fork -y
choco install golang -y
choco install httpie -y
choco install jetbrainstoolbox -y
choco install jq -y
choco install lens -y
choco install kubernetes-helm -y
choco install kustomize -y
choco install minikube -y
choco install nerd-fonts-delugiacomplete -y
choco install nerd-fonts-delugiamono-complete -y
choco install nodejs -y
choco install nswagstudio -y
choco install oh-my-posh -y
choco install openjdk -y
choco install openssl -y
choco install poshgit -y
choco install postman -y
choco install python3 -y
choco install rdm -y
choco install rufus -y
choco install ServiceBusExplorer -y
choco install slack -y
choco install sublimetext4 -y
choco install sysinternals -y
choco install terraform -y
choco install totalcommander -y
choco install volta -y
choco install vscodium -y
choco install winmerge -y